### ISSUE TITLE
liveness probe checks for server

### ISSUE THREAD

**Issue by arm2arm** [sagemathinc/cocalc-kubernetes#10]
which URL should I use for the liveness probe checks??
are there spacial url which checks the pings??

**Comment by williamstein** [comment]
Here's what we use on cocalc.com:
```
        livenessProbe:
          httpGet:
            path: /concurrent-warn
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 120
          failureThreshold: 3
          periodSeconds:  5
          timeoutSeconds: 10
```

It's important to also put this in the yaml for the server or somehow set this var:
```
        env:
          - name: SMC_DB_CONCURRENT_WARN
            value: "200"
```
