### ISSUE TITLE
test and provide step-by-step instructions for install cocalc-kubernetes into minikube

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc-kubernetes#16]
Motivation: It does not seem to just work with the default minikube, due to lack of nfs support.

**Comment by williamstein** [comment]
This is much more complicated than it sounds, since there are so many different ways to run minikube:
```
  - kvm2:
  - none: 
  - podman:
  - virtualbox:
  - vmware:
  - docker:
```
